### ISSUE TITLE
Is this a Bug？

### ISSUE THREAD

**Issue by itachiliu** [niclabs/dns-tools#17]
When I use the branch V1.1.0 of HSM-Tool, after compilation, execute “ ./hsm-tools sign pkcs11 -p ./dtc.so -f ./example.com -3 -z example.com -o example.com.signed -c”，the Error "Error: Input File Path not Specified" occurs.But there is no problem with using other versions.

**Comment by eriverosr** [comment]
You are right, flag parsing is bugged in v1.1.0. v1.1.1 fixes it. I think we could delete the broken version to avoid future problems.

**Comment by itachiliu** [comment]
> You are right, flag parsing is bugged in v1.1.0. v1.1.1 fixes it. I think we could delete the broken version to avoid future problems.

OK. Thank you.I think you can update the readme.md file first. The description is still wrong.

**Comment by itachiliu** [comment]
I took a look at the code, and you're using SQlitE3 as a way to store keys, but SQlitE3 is a localized database, isn't that safe?

**Comment by eriverosr** [comment]
If by "localized database" you mean the database is a local file and that could be insecure, we think that with a good configuration (well defined permissions in the database and config files) you should not have problems with data exfiltration. In case you think another storage system could be better for your use case, you could extend it, creating another struct that follows the `[Storage](https://github.com/niclabs/dtc/blob/master/storage.go)` interface and another [Config](https://github.com/niclabs/dtc/blob/master/config/sqlite3.go) definition.

In any case, your question is more related to [DTC](https://github.com/niclabs/dtc) than this repo, so I recommend you to use the issues on its respective repository.

**Comment by itachiliu** [comment]
> If by "localized database" you mean the database is a local file and that could be insecure, we think that with a good configuration (well defined permissions in the database and config files) you should not have problems with data exfiltration. In case you think another storage system could be better for your use case, you could extend it, creating another struct that follows the `[Storage](https://github.com/niclabs/dtc/blob/master/storage.go)` interface and another [Config](https://github.com/niclabs/dtc/blob/master/config/sqlite3.go) definition.
> 
> In any case, your question is more related to [DTC](https://github.com/niclabs/dtc) than this repo, so I recommend you to use the issues on its respective repository.

OK，Thanks. I will close the issue.
