### ISSUE TITLE
root file can not be sign.

### ISSUE THREAD

**Issue by itachiliu** [niclabs/dns-tools#18]
I have a problem. I  download root.zone from the root server and delete the signature information in it,then re-sign it with `./dns-tools sign pkcs11 -p ./dtc.so -f ./root.zone -3 -z . -o root.zone.signed -c`, and I find it cannot be signed.
Suggested message:
 **Cannot sign RRSig: PKcs11:0xC0: CKR_SIGNATURE_INVALID**.

dtc.log err info :
2020/12/07 14:04:46 signFinal ended
**2020/12/07 14:04:46 verifyRSA: invalid signature
2020/12/07 14:04:46 [verifyRSA] invalid signature [Code 192]**
2020/12/07 14:04:46 Called: C_Logout
2020/12/07 14:04:46 Logged out.
2020/12/07 14:04:46 Called: C_CloseSession
2020/12/07 14:04:46 Called: C_Finalize
2020/12/07 14:04:46 stopping listening of messages
2020/12/07 14:04:46 stopping listening of messages

root.zone file:
[root.zone](https://github.com/itachiliu/root.zone/blob/master/root.zone)

Is there any problem with my operation, or is it due to other reasons,and what does the   [Code 192] mean in dtc.log?

**Comment by eriverosr** [comment]
Hello. Code 192 (0xC0) is the error code number for CKR_SIGNATURE_INVALID in [PKCS#11 specification](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html). That means the signature generated was not valid. 

What version of the library did you use? I will try to replicate your configuration meanwhile.

**Comment by eriverosr** [comment]
I think I found the bugs related to your problem. Try with the latest versions of each tool:
- dns-tools v2.3.1 
- dtc v3.1.1
- dtcnode v3.0.3

Thanks for your feedback!

**Comment by itachiliu** [comment]
> I think I found the bugs related to your problem. Try with the latest versions of each tool:
> 
> * dns-tools v2.3.1
> * dtc v3.1.1
> * dtcnode v3.0.3
> 
> Thanks for your feedback!

OK, I will try it. Thanks for your reply.
