### ISSUE TITLE
signed file support the ldns-verify-zone tool to verify ?

### ISSUE THREAD

**Issue by itachiliu** [niclabs/dns-tools#19]
After a complete process, the signature file is obtained. When I use the  ldns-verify-zone tool to verify the file, the error occured. The error is :
………………
**Error: b.nic.zuerich. has an NSEC(3), but is glue
Error: c.nic.zuerich.	A has signature(s), but is glue
Error: c.nic.zuerich.	AAAA has signature(s), but is glue
Error: c.nic.zuerich. has an NSEC(3), but is glue
Error: d.nic.zuerich.	A has signature(s), but is glue
Error: d.nic.zuerich.	AAAA has signature(s), but is glue
Error: d.nic.zuerich. has an NSEC(3), but is glue
Error: there is no NSEC(3) for zw.
Error: ns1.telone.co.zw.	A has signature(s), but is glue
Error: ns1.telone.co.zw.	AAAA has signature(s), but is glue
Error: ns1.telone.co.zw. has an NSEC(3), but is glue
Error: ns1zim.telone.co.zw.	A has signature(s), but is glue
Error: ns1zim.telone.co.zw.	AAAA has signature(s), but is glue
Error: ns1zim.telone.co.zw. has an NSEC(3), but is glue
Error: ns2.telone.co.zw.	A has signature(s), but is glue
Error: ns2.telone.co.zw.	AAAA has signature(s), but is glue
Error: ns2.telone.co.zw. has an NSEC(3), but is glue
Error: ns2zim.telone.co.zw.	A has signature(s), but is glue
Error: ns2zim.telone.co.zw.	AAAA has signature(s), but is glue
Error: ns2zim.telone.co.zw. has an NSEC(3), but is glue
There were errors in the zone**

**Comment by eriverosr** [comment]
Hello and thanks again for your reports. There was a problem with the glue RRSet identification. It is fixed in v2.3.2, and ldns-verify-zone should validate correctly the signed output of your root.zone file (I am assuming you are using the same root.zone you sent some issues ago). 

However, you are still going to receive some errors when validating that zone. ldns-verify-zone will detect that the A/AAAA type RRs with owner name `a.root-servers.net` are glue and should not be signed, but the zone does not define them explicitly as NS servers for the root zone. If you add the NS RRs to the root.zone file (you can get them from the example dig query at the end of this message), it should validate.

```
➜  ~ dig -tNS .       

; <<>> DiG 9.16.9 <<>> -tNS .
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20858
;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;.				IN	NS

;; ANSWER SECTION:
.			509676	IN	NS	a.root-servers.net.
.			509676	IN	NS	b.root-servers.net.
.			509676	IN	NS	c.root-servers.net.
.			509676	IN	NS	d.root-servers.net.
.			509676	IN	NS	e.root-servers.net.
.			509676	IN	NS	f.root-servers.net.
.			509676	IN	NS	g.root-servers.net.
.			509676	IN	NS	h.root-servers.net.
.			509676	IN	NS	i.root-servers.net.
.			509676	IN	NS	j.root-servers.net.
.			509676	IN	NS	k.root-servers.net.
.			509676	IN	NS	l.root-servers.net.
.			509676	IN	NS	m.root-servers.net.

;; Query time: 6 msec
;; SERVER: xxx.xxx.xxx.xxx#53(xxx.xxx.xxx.xxx)
;; WHEN: Wed Dec 23 20:25:44 -03 2020
;; MSG SIZE  rcvd: 239
```

Let me know if it works for you now.

**Comment by itachiliu** [comment]
> Hello and thanks again for your reports. There was a problem with the glue RRSet identification. It is fixed in v2.3.2, and ldns-verify-zone should validate correctly the signed output of your root.zone file (I am assuming you are using the same root.zone you sent some issues ago).
> 
> However, you are still going to receive some errors when validating that zone. ldns-verify-zone will detect that the A/AAAA type RRs with owner name `a.root-servers.net` are glue and should not be signed, but the zone does not define them explicitly as NS servers for the root zone. If you add the NS RRs to the root.zone file (you can get them from the example dig query at the end of this message), it should validate.
> 
> ```
> ➜  ~ dig -tNS .       
> 
> ; <<>> DiG 9.16.9 <<>> -tNS .
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20858
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1232
> ;; QUESTION SECTION:
> ;.				IN	NS
> 
> ;; ANSWER SECTION:
> .			509676	IN	NS	a.root-servers.net.
> .			509676	IN	NS	b.root-servers.net.
> .			509676	IN	NS	c.root-servers.net.
> .			509676	IN	NS	d.root-servers.net.
> .			509676	IN	NS	e.root-servers.net.
> .			509676	IN	NS	f.root-servers.net.
> .			509676	IN	NS	g.root-servers.net.
> .			509676	IN	NS	h.root-servers.net.
> .			509676	IN	NS	i.root-servers.net.
> .			509676	IN	NS	j.root-servers.net.
> .			509676	IN	NS	k.root-servers.net.
> .			509676	IN	NS	l.root-servers.net.
> .			509676	IN	NS	m.root-servers.net.
> 
> ;; Query time: 6 msec
> ;; SERVER: xxx.xxx.xxx.xxx#53(xxx.xxx.xxx.xxx)
> ;; WHEN: Wed Dec 23 20:25:44 -03 2020
> ;; MSG SIZE  rcvd: 239
> ```
> 
> Let me know if it works for you now.

Thanks, I will try it. and send the feedback to you.

**Comment by itachiliu** [comment]
> Hello and thanks again for your reports. There was a problem with the glue RRSet identification. It is fixed in v2.3.2, and ldns-verify-zone should validate correctly the signed output of your root.zone file (I am assuming you are using the same root.zone you sent some issues ago).
> 
> However, you are still going to receive some errors when validating that zone. ldns-verify-zone will detect that the A/AAAA type RRs with owner name `a.root-servers.net` are glue and should not be signed, but the zone does not define them explicitly as NS servers for the root zone. If you add the NS RRs to the root.zone file (you can get them from the example dig query at the end of this message), it should validate.
> 
> ```
> ➜  ~ dig -tNS .       
> 
> ; <<>> DiG 9.16.9 <<>> -tNS .
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20858
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1232
> ;; QUESTION SECTION:
> ;.				IN	NS
> 
> ;; ANSWER SECTION:
> .			509676	IN	NS	a.root-servers.net.
> .			509676	IN	NS	b.root-servers.net.
> .			509676	IN	NS	c.root-servers.net.
> .			509676	IN	NS	d.root-servers.net.
> .			509676	IN	NS	e.root-servers.net.
> .			509676	IN	NS	f.root-servers.net.
> .			509676	IN	NS	g.root-servers.net.
> .			509676	IN	NS	h.root-servers.net.
> .			509676	IN	NS	i.root-servers.net.
> .			509676	IN	NS	j.root-servers.net.
> .			509676	IN	NS	k.root-servers.net.
> .			509676	IN	NS	l.root-servers.net.
> .			509676	IN	NS	m.root-servers.net.
> 
> ;; Query time: 6 msec
> ;; SERVER: xxx.xxx.xxx.xxx#53(xxx.xxx.xxx.xxx)
> ;; WHEN: Wed Dec 23 20:25:44 -03 2020
> ;; MSG SIZE  rcvd: 239
> ```
> 
> Let me know if it works for you now.

Sorry . This reply is late,  I add the NS
`.			518400	IN	NS	a.root-servers.net.`
`.			518400	IN	NS	b.root-servers.net.`
`.			518400	IN	NS	c.root-servers.net.`
`.			518400	IN	NS	d.root-servers.net.`
`.			518400	IN	NS	e.root-servers.net.`
`.			518400	IN	NS	f.root-servers.net.`
`.			518400	IN	NS	g.root-servers.net.`
`.			518400	IN	NS	h.root-servers.net.`
`.			518400	IN	NS	i.root-servers.net.`
`.			518400	IN	NS	j.root-servers.net.`
`.			518400	IN	NS	k.root-servers.net.`
`.			518400	IN	NS	l.root-servers.net.`
`.			518400	IN	NS	m.root-servers.net.`

and resign.
Then executed **ldns-verify-zone root.zone.signed**
 the same error occur. 

**Error: there is no NSEC(3) for zone.
Error: there is no NSEC(3) for zuerich.
Error: a.nic.zuerich.	A has signature(s), but is glue
Error: a.nic.zuerich.	AAAA has signature(s), but is glue
Error: a.nic.zuerich. has an NSEC(3), but is glue
Error: b.nic.zuerich.	A has signature(s), but is glue
Error: b.nic.zuerich.	AAAA has signature(s), but is glue
Error: b.nic.zuerich. has an NSEC(3), but is glue
Error: c.nic.zuerich.	A has signature(s), but is glue
Error: c.nic.zuerich.	AAAA has signature(s), but is glue
Error: c.nic.zuerich. has an NSEC(3), but is glue
Error: d.nic.zuerich.	A has signature(s), but is glue
Error: d.nic.zuerich.	AAAA has signature(s), but is glue
Error: d.nic.zuerich. has an NSEC(3), but is glue
Error: there is no NSEC(3) for zw.
Error: ns1.telone.co.zw.	A has signature(s), but is glue
Error: ns1.telone.co.zw.	AAAA has signature(s), but is glue
Error: ns1.telone.co.zw. has an NSEC(3), but is glue
Error: ns1zim.telone.co.zw.	A has signature(s), but is glue
Error: ns1zim.telone.co.zw.	AAAA has signature(s), but is glue
Error: ns1zim.telone.co.zw. has an NSEC(3), but is glue
Error: ns2.telone.co.zw.	A has signature(s), but is glue
Error: ns2.telone.co.zw.	AAAA has signature(s), but is glue
Error: ns2.telone.co.zw. has an NSEC(3), but is glue
Error: ns2zim.telone.co.zw.	A has signature(s), but is glue
Error: ns2zim.telone.co.zw.	AAAA has signature(s), but is glue
Error: ns2zim.telone.co.zw. has an NSEC(3), but is glue
There were errors in the zone**

This the root.zone file:
[root.zone](https://github.com/itachiliu/root.zone/blob/master/root.zone)

**Comment by eriverosr** [comment]
> This the root.zone file:

The last commit of your root zone is not complete. I used [this commit](https://github.com/itachiliu/root.zone/commit/afb114a55faacedfe30769c2b0c97d1ecc2b214b#diff-e4dd9ee49d5173f498d1ec8c229f88636d2bba2a450f29f1ad907f9c33171a52) that appears to be more complete, but with the root NS servers added as mentioned before.

If you need to compare it with the zone I'm using, I've uploaded it [here](https://gist.github.com/eriverosr/55c35d998e2052a6761fe8e82b99affd). Tell me if you have problems using this version.

**Comment by itachiliu** [comment]
> > This the root.zone file:
> 
> The last commit of your root zone is not complete. I used [this commit](https://github.com/itachiliu/root.zone/commit/afb114a55faacedfe30769c2b0c97d1ecc2b214b#diff-e4dd9ee49d5173f498d1ec8c229f88636d2bba2a450f29f1ad907f9c33171a52) that appears to be more complete, but with the root NS servers added as mentioned before.
> 
> If you need to compare it with the zone I'm using, I've uploaded it [here](https://gist.github.com/eriverosr/55c35d998e2052a6761fe8e82b99affd). Tell me if you have problems using this version.

I try the file you upload. the same error appeard, and I compare [the file you uploaded ](https://gist.github.com/eriverosr/55c35d998e2052a6761fe8e82b99affd)  with [root.zone](https://github.com/itachiliu/root.zone/blob/master/root.zone)(I have updated it.), everything is the same except TTL.

**Comment by eriverosr** [comment]
I cannot see that they are the same files. The file I uploaded has 14853 lines and your root.zone file has 4698 lines. Also, you can check the last line of each file: in your case, the last RR is `ga.` and in my case, the last RR is `ns2zim.telone.co.zw.`

**Comment by itachiliu** [comment]
> I cannot see that they are the same files. The file I uploaded has 14853 lines and your root.zone file has 4698 lines. Also, you can check the last line of each file: in your case, the last RR is `ga.` and in my case, the last RR is `ns2zim.telone.co.zw.`

Sorry. I have tried your version [(gistfile1.txt](https://gist.github.com/eriverosr/55c35d998e2052a6761fe8e82b99affd)), there are still errors.
……
Error: ns2.telone.co.zw. has an NSEC(3), but is glue
Error: ns2zim.telone.co.zw. A has signature(s), but is glue
Error: ns2zim.telone.co.zw. AAAA has signature(s), but is glue
Error: ns2zim.telone.co.zw. has an NSEC(3), but is glue
There were errors in the zone

**Comment by eriverosr** [comment]
I downloaded the file I uploaded before and I had no problem signing it again. Can you send me the following information?
- dns-tools version
- the commands and args you are using (for ldns and dns-tools)
- ldns and dns-tools log files
- The SHA256 hash of the zone file you are signing (mine is `72fad3f86c5e73e5a13697913c2401b616b4d92147e632e69339c66e4b62e595`  )
Thanks in advance!

**Comment by itachiliu** [comment]
> I downloaded the file I uploaded before and I had no problem signing it again. Can you send me the following information?
> 
> * dns-tools version
> * the commands and args you are using (for ldns and dns-tools)
> * ldns and dns-tools log files
> * The SHA256 hash of the zone file you are signing (mine is `72fad3f86c5e73e5a13697913c2401b616b4d92147e632e69339c66e4b62e595`  )
>   Thanks in advance!


Sorry, when I rebuild the dns-tools, the result is correct. Thanks for your explain and sorry to trouble you. 

This is my version(correct result):
dns-tools version : v2.3.2 (commit ID : 489de2193d08f6a3090ede2ae80c25e2f5240e12)
dtcnode version :  v3.0.3(commit ID : e1fb44ac55a1b85df22c4fe5bb978aff866a9b5b)
dns-tools commands : `./dns-tools sign pkcs11 -p ./dtc.so -f ./root.zone  -z . -o root.zone.signed`
ldns commands : `ldns-verify-zone root.zone.signed`
The SHA256 hash : 72fad3f86c5e73e5a13697913c2401b616b4d92147e632e69339c66e4b62e595
