### ISSUE TITLE
File sign problem.

### ISSUE THREAD

**Issue by itachiliu** [niclabs/dns-tools#21]
I use the **dnssec-keygen** to generate two keys：
Kkbenet.com.%2B003%2B00851.key.+005+37875**.key**
Kkbenet.com.%2B003%2B00851.key.+005+37875**.private** and sign the zone with it.
The dns-tools have two key files(KSK and ZSK) to sign the zone, but its format is **.pem**.
The question is : if I want to use the key which is generated by  **dnssec-keygen** to sign the zone file, any methods can be adopted? Or do  I have anyway to change the **.key** and **.private** to **.pem**?

**Comment by madestro** [comment]
Hi! you have to change to .pem, we have not implemented reading the keys in another format (yet).
