### ISSUE TITLE
Sign domain and subdomains together

### ISSUE THREAD

**Issue by dotsensei** [niclabs/dns-tools#22]
Hi,
Is it possible to sign with your tool both the domain and the subdomains (for which DS and NS records are provided, they use their own DNS servers.)

Thank you.

**Comment by madestro** [comment]
do you mean 2+ zone files in batch or a huge zone file with all domains and subdomains?

**Comment by dotsensei** [comment]
Huge zone with all domains and subdomains, or more exactly - a TLD zone.

**Comment by madestro** [comment]
hmm, if i understand, you have a tld zone with all the hierarchy? e.g:  .ple. , .exam.ple. , www.exam.ple.  and you want all the hierarchy signed automatically? try it using the TLD as name to sign.  We have tested it signing a root zone (using name=.)
