### ISSUE TITLE
NSEC3 salt and iterations

### ISSUE THREAD

**Issue by huguei** [niclabs/dns-tools#24]
Hi. I couldn't find a way to configure the salt and iterations in case of NSEC3 signing.
I think the default should be empty salt and 0 iterations, as is the current recommendations, but it should be configurable with something like ```[--nsec3-iterations [0..100]] [--nsec3-salt-length [1..64]|--nsec3-salt-value <string>]``` (if given only salt-length, it should generate a random one with the provided length)
Thanks.

**Comment by eriverosr** [comment]
Done in latest commit :)
