### ISSUE TITLE
RRSIG doesn't validate DNSKEY

### ISSUE THREAD

**Issue by madestro** [niclabs/dns-tools#6]

**Comment by eriverosr** [comment]
I found the problem:

First of all, the decryption problem works almost fine, but the "hash" section of the decrypted data does not match with the data signed.

After some debugging, I noticed that the PKCS#11 specification requires the original data provided as argument to the function, but the actual implementation passes the hash of the data. So, the HSM hashes again the data provided. I checked comparing the hash section from the decrypted signature in the `Verify` function with the value obtained if I hash again the data provided to the HSM `sign` function and they match.

So, it seems that the API for crypto.Signer is not fully compatible with the PKCS#11 API :(

**Comment by eriverosr** [comment]
I correct myself: the problem was not incompatibility between both APIs. The PKCS#11 API has an option to sign an already hashed message. I corrected and uploaded the implementation with the correct Sign Mechanism inspired by [this library](https://github.com/ThalesIgnite/crypto11).
